// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOWBJNgw6JFfKvQqz05OmD3LvAH3fKaNE',
    appId: '1:589968609200:web:5a248479f83e518b985075',
    messagingSenderId: '589968609200',
    projectId: 'dating-59830',
    authDomain: 'dating-59830.firebaseapp.com',
    storageBucket: 'dating-59830.appspot.com',
    measurementId: 'G-NXRTVFD5KV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5ySTAYSBvGzrEEGpHnM16UjS822sdcOo',
    appId: '1:589968609200:android:2429a60bbeaf7bdd985075',
    messagingSenderId: '589968609200',
    projectId: 'dating-59830',
    storageBucket: 'dating-59830.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4EA7MprFk0iFDyrF4hmYDAf9GTJ9lbdA',
    appId: '1:589968609200:ios:3de8d3a500856a4b985075',
    messagingSenderId: '589968609200',
    projectId: 'dating-59830',
    storageBucket: 'dating-59830.appspot.com',
    iosBundleId: 'com.example.datingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4EA7MprFk0iFDyrF4hmYDAf9GTJ9lbdA',
    appId: '1:589968609200:ios:1cdc1c4a36260929985075',
    messagingSenderId: '589968609200',
    projectId: 'dating-59830',
    storageBucket: 'dating-59830.appspot.com',
    iosBundleId: 'com.example.datingApp.RunnerTests',
  );
}
